DROP TABLE IF EXISTS DEPARTMENT CASCADE;

CREATE TABLE DEPARTMENT
(
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    login_id        VARCHAR(256)    NOT NULL,
    login_pw        VARCHAR(256)    NOT NULL,
    field           VARCHAR(256)    NOT NULL,
    detail_field    VARCHAR(256),
    master          BOOL            DEFAULT FALSE,
    admin           BOOL            DEFAULT FALSE,
    commit          BOOL            DEFAULT FALSE,
    insert_date     DATETIME,
    update_date     DATETIME
);

DROP TABLE IF EXISTS REQUEST CASCADE;

CREATE TABLE REQUEST
(
    id                          VARCHAR(256)    NOT NULL,
    department_id               BIGINT          NOT NULL,
    request                     VARCHAR(512)    NOT NULL,
    status                      VARCHAR(16)     NOT NULL,
    area                        VARCHAR(8)      NOT NULL,
    detail_area                 VARCHAR(64)     NOT NULL,
    request_date                DATETIME,
    complete_date               DATETIME,
    expected_complete_date      DATETIME,
    insert_date                 DATETIME,
    update_date                 DATETIME
);

DROP TABLE IF EXISTS COMMENT CASCADE;

CREATE TABLE COMMENT
(
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    department_id       BIGINT          NOT NULL,
    comment             VARCHAR(512)    NOT NULL,
    request_id          VARCHAR(256)    NOT NULL,
    parent_comment_id   BIGINT,
    insert_date         DATETIME,
    update_date         DATETIME
);

DROP TABLE IF EXISTS COMMENTFILE CASCADE;

CREATE TABLE COMMENTFILE
(
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    comment_id      BIGINT          NOT NULL,
    original_name   VARCHAR(512)    NOT NULL,
    store_file_name       VARCHAR(512)    NOT NULL,
    insert_date     DATETIME
);